# Generated by Django 3.1 on 2020-08-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200811_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='verify_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='verify_status',
            field=models.DecimalField(decimal_places=0, default=True, max_digits=10),
            preserve_default=False,
        ),
    ]
