# Generated by Django 3.1 on 2020-08-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200813_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='verify_status',
        ),
    ]
