# Generated by Django 3.1 on 2020-08-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_userdata_verify_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='verify_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
