# Generated by Django 3.1 on 2020-08-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userdata_verify_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='login_first',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
