# Generated by Django 3.1 on 2020-09-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userdata_login_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='dob',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
