# Generated by Django 3.1 on 2020-09-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userdata_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='bio',
            field=models.CharField(default=False, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='education',
            field=models.CharField(default=False, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='skills',
            field=models.CharField(default=False, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='dob',
            field=models.CharField(default=False, max_length=250, null=True),
        ),
    ]
