# Generated by Django 3.1 on 2020-09-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200906_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profile_img',
            field=models.CharField(default=False, max_length=1000, null=True),
        ),
    ]
